name: CI

on:
  push:
    branches: [ gh-actions ]
  schedule:
    - cron: '0 * * * *'

jobs:
  push-branches:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          $GITHUB_WORKSPACE/push-branches.sh
        env:
          TOKEN_WORKFLOW: ${{ secrets.TOKEN_WORKFLOW }}
